### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zavalacl/updatedproj4#1]
:+1: Looking very nice! I really like how many Bootstrap components you've managed to include. This looks really polished.
### Getting rid of `.DS_Store` clutter

OS X automatically generates hidden `.DS_Store` files and by default, Git will include them your commits. To get rid of this clutter in our Git repos, you can [check out this link](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).
### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.

**Comment by zavalacl** [comment]
Awesome! Just out of curiosity, when you close a thread does that mean that the assignment is closed from any further improvements you highlighted? Thanks and Happy Friday! :)

**Comment by chrisvfritz** [comment]
Great question! I close the issue and give a :+1: to show that nothing else _needs_ to be fixed for this project. It's considered accepted and you've earned a 4.0 on it. You can still update it if you'd like, but I'll only look at it again if you post a comment like you just did. :smiley:

If you'd like to continue expanding on a project once it's been accepted, as some students like to do for some projects, I'm happy to keep giving you feedback until I can't find anything else that could possibly be improved. All you have to do is ask me here to take another look.

Does that make sense?
